services:
  ##############################################################################
  # DEVELOPMENT CONTAINER SERVICE                                              #
  ##############################################################################
  devcontainer:
    # --------------------------------------------------------------------------
    # IMAGE
    # --------------------------------------------------------------------------
    # This image and this digest give the container for the development
    # environment.
    image: "mcr.microsoft.com/devcontainers/base@sha256:55126de3b3e113096201055951b4cb717900bafb379c59dcbada65c49cd7ce22" # jammy

    # --------------------------------------------------------------------------
    # TTY
    # --------------------------------------------------------------------------
    # If you set this directive to true, the service gets a pseudo-TTY. A
    # process that stays active needs a pseudo-TTY. An interactive shell
    # session also needs a pseudo-TTY.
    tty: true

    # --------------------------------------------------------------------------
    # VOLUMES
    # --------------------------------------------------------------------------
    # These volumes are the mount points between the host system and the
    # container.
    volumes:
      - ..:/workspace

    # --------------------------------------------------------------------------
    # ENVIRONMENT VARIABLES
    # --------------------------------------------------------------------------
    # These environment variables go into the container. They configure the
    # development environment.
    environment:
      DOCKER_HOST: "tcp://docker-in-docker:2375"

  ##############################################################################
  # DOCKER-IN-DOCKER SERVICE                                                   #
  ##############################################################################
  docker-in-docker:
    # --------------------------------------------------------------------------
    # IMAGE
    # --------------------------------------------------------------------------
    # This image and this digest give the container for the Docker-in-Docker
    # service.
    image: "docker.io/docker@sha256:bfec1f5159c63a81ca6fdedbd81404d2c0e16378ed0feec3bb3fbf3998847659" # 29.6.2

    # --------------------------------------------------------------------------
    # PRIVILEGED MODE
    # --------------------------------------------------------------------------
    # If you set this directive to true, the container runs in privileged
    # mode. Docker-in-Docker needs privileged mode to operate correctly.
    privileged: true

    # --------------------------------------------------------------------------
    # VOLUMES
    # --------------------------------------------------------------------------
    # These volumes are the mount points between the host system and the
    # container.
    volumes:
      - ..:/workspace

    # --------------------------------------------------------------------------
    # ENVIRONMENT VARIABLES
    # --------------------------------------------------------------------------
    # These environment variables go into the container. They configure the
    # Docker daemon and the Docker client.
    environment:
      DOCKER_TLS_CERTDIR: ""

  ##############################################################################
  # ZOT REGISTRY SERVICE                                                       #
  ##############################################################################
  zot-registry:
    # --------------------------------------------------------------------------
    # IMAGE
    # --------------------------------------------------------------------------
    # This image and this digest give the container for the Zot registry
    # service.
    image: "ghcr.io/project-zot/zot@sha256:6f7bf2b8e43437c7c3a121bc80214845c85f27321e66f2ff4be6bf4220775fd7" # v2.1.18

    # --------------------------------------------------------------------------
    # PORTS
    # --------------------------------------------------------------------------
    # These ports are the mappings between the host system and the container.
    ports:
      - "5000:5000"