name: "CI"

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: "read"
  packages: "write"

jobs:
  nix:
    runs-on: "ubuntu-latest"

    container:
      image: "docker.io/nixos/nix@sha256:b9c9611c8530fa8049a1215b20638536e1e71dcaf85212e47845112caf3adeea" # v2.34.0
      env:
        NIX_CONFIG: "experimental-features = nix-command flakes"

    steps:
      - name: "GitHub: Checkout Repository"
        run: |
          git init --quiet --initial-branch "main"
          git config --global --add safe.directory "*"
          git remote add origin "${{ github.server_url }}/${{ github.repository }}"
          git config --local http.${{ github.server_url }}/.extraheader "Authorization: basic $(echo -n "x-access-token:${{ github.token }}" | base64 --wrap=0)"
          git fetch --quiet --no-tags --depth=1 origin "${{ github.ref }}"
          git checkout --quiet "${{ github.sha }}"
      - name: "Task: Deploy"
        shell: >
          nix develop
          --ignore-env
          --keep-env-var CI
          --keep-env-var HOME
          --keep-env-var REF_NAME
          --keep-env-var NIX_CONFIG
          --keep-env-var CONTAINER_REGISTRY
          --keep-env-var CONTAINER_REGISTRY_USERNAME
          --keep-env-var CONTAINER_REGISTRY_PASSWORD
          --keep-env-var IMAGE_NAMESPACE
          .#ciEnvironment
          -c bash -eo pipefail {0}
        run: "task deploy"
        env:
          REF_NAME: "${{ github.ref_name }}"

          CONTAINER_REGISTRY: "ghcr.io"
          CONTAINER_REGISTRY_USERNAME: "${{ github.repository_owner }}"
          CONTAINER_REGISTRY_PASSWORD: "${{ secrets.GITHUB_TOKEN }}"

          IMAGE_NAMESPACE: "${{ github.repository_owner }}"